// data-2026-06.js — stories for June 2026.
// Loaded on-demand by app.js and edition.js; never loaded on its own.
// To add a new day: append a new object to window.DAILY_NEWS_STORIES["YYYY-MM-DD"].

(function () {
  window.DAILY_NEWS_STORIES = window.DAILY_NEWS_STORIES || {};

  window.DAILY_NEWS_STORIES["2026-06-13"] = [
    { id: "taiwan-strait-frigate", category: "international", image: "city", lead: false, author: "Maya Chen", read: 5, title: { en: "China says it tracked a Dutch frigate through the Taiwan Strait", zh: "中國稱在台灣海峽全程跟監荷蘭巡防艦" }, dek: { en: "Beijing publicized the transit as another sign of rising scrutiny over freedom of navigation around Taiwan and the wider region.", zh: "北京高調談論這次航行，再度凸顯台灣周邊與更廣泛區域的航行自由議題正受到更高關注。" } },
    { id: "iran-peace-hormuz", category: "international", image: "meeting", lead: true, author: "Maya Chen", read: 7, title: { en: "U.S. and Iran signal peace deal is near as fighting flares near Hormuz", zh: "美伊釋出接近和平協議訊號，但荷莫茲附近仍爆發衝突" }, dek: { en: "Reuters reported both sides had broadly agreed on a draft, yet fresh military action near the strait showed how fragile any settlement remains.", zh: "路透報導雙方大致同意一份協議文本，但海峽附近再起軍事行動，顯示任何停火安排都仍十分脆弱。" } },
    { id: "eu-russia-banks-sanctions", category: "international", image: "policy", lead: false, author: "Maya Chen", read: 5, title: { en: "EU lines up a 21st sanctions package against Russia focused on banks", zh: "歐盟規劃第 21 輪對俄制裁，重點鎖定銀行體系" }, dek: { en: "The European Commission's latest package aims to tighten financial pressure as the war in Ukraine and its spillover risks continue.", zh: "歐盟執委會最新方案意在進一步加大金融壓力，因烏克蘭戰爭及其外溢風險仍持續。" } },
    { id: "g7-ai-online-safety", category: "international", image: "meeting", lead: false, author: "Maya Chen", read: 4, title: { en: "Tech executives head to the G7 as leaders put AI and online safety on the agenda", zh: "科技高層將赴 G7 峰會，AI 與網路安全列入議程" }, dek: { en: "France's summit planning shows digital governance is now inseparable from geopolitics, trade and alliance management.", zh: "法國主辦峰會的安排顯示，數位治理已與地緣政治、貿易和同盟協調緊密相連。" } },
    { id: "eurodac-launch-glitch", category: "international", image: "data", lead: false, author: "Maya Chen", read: 4, title: { en: "EU asylum database falters on the first day of the migration pact launch", zh: "歐盟移民新協議上路首日，庇護資料庫即發生故障" }, dek: { en: "A malfunction in Eurodac undercut the rollout of the bloc's migration framework and highlighted how dependent border policy has become on digital systems.", zh: "Eurodac 故障削弱了歐盟移民框架的首日啟動，也凸顯邊境政策如今高度仰賴數位系統。" } },

    { id: "computex-ai-taiwan", category: "technology", image: "technology", lead: true, author: "Iris Park", read: 6, title: { en: "Computex puts Taiwan's expanding role in global AI infrastructure at center stage", zh: "台北國際電腦展凸顯台灣在全球 AI 基礎設施中的擴大角色" }, dek: { en: "Reuters described executives flocking to Taipei even as military pressure loomed, underscoring Taiwan's central place in the AI hardware ecosystem.", zh: "路透指出，即使軍事壓力升高，全球高層仍湧向台北，凸顯台灣在 AI 硬體生態系中的核心地位。" } },
    { id: "ai-power-water-demand", category: "technology", image: "data", lead: false, author: "Iris Park", read: 5, title: { en: "UN researchers say AI could double data-centre power and water use by 2030", zh: "聯合國研究人員稱 AI 可能在 2030 年前讓資料中心電力與用水需求翻倍" }, dek: { en: "The forecast sharpened concerns that the AI boom is colliding with physical constraints in grids, cooling systems and water supply.", zh: "這項預測加深外界憂慮：AI 熱潮正與電網、冷卻系統及水資源等實體限制正面碰撞。" } },
    { id: "nvidia-humanoid-partners", category: "technology", image: "technology", lead: false, author: "Iris Park", read: 4, title: { en: "Nvidia broadens humanoid robot partnerships beyond China", zh: "輝達將人形機器人合作擴大至中國以外地區" }, dek: { en: "The chip designer said it will work with robot makers in the U.S., Europe and South Korea, widening the race to turn AI into physical machines.", zh: "這家晶片設計商表示，將與美國、歐洲與南韓的機器人業者合作，擴大把 AI 轉化為實體機器的競賽。" } },
    { id: "arm-datacentre-customers", category: "technology", image: "data", lead: false, author: "Iris Park", read: 4, title: { en: "Arm says ByteDance and Oracle are using its data-centre chips", zh: "Arm 表示字節跳動與甲骨文正採用其資料中心晶片" }, dek: { en: "The disclosure signaled broader commercial traction for Arm's server ambitions as AI infrastructure buyers diversify their chip stacks.", zh: "這項揭露顯示，隨著 AI 基礎設施買家分散晶片配置，Arm 在伺服器市場的布局正獲得更廣泛商業進展。" } },
    { id: "xpeng-iron-robots", category: "technology", image: "technology", lead: false, author: "Iris Park", read: 4, title: { en: "Xpeng says humanoid mass production is drawing closer", zh: "小鵬稱人形機器人大規模量產已愈來愈近" }, dek: { en: "The automaker's push into so-called physical AI reflects how EV groups are searching for the next growth platform beyond cars.", zh: "這家車廠進軍所謂「物理 AI」，反映電動車企業正尋找汽車以外的下一個成長平台。" } },

    { id: "taipower-avoid-relegation", category: "sports", image: "stadium", lead: false, author: "Leo Huang", read: 3, title: { en: "Taipower defeat Desafio to stay up in Taiwan's top football league", zh: "台電擊敗 Desafio，保住台灣足球頂級聯賽席次" }, dek: { en: "Taipower sealed safety with a 3-0 win in Kaohsiung, closing the domestic season with a clear statement in the relegation playoff.", zh: "台電在高雄以 3 比 0 獲勝，於升降賽中強勢保級，為國內賽季劃下明確句點。" } },
    { id: "mexico-world-cup-opener", category: "sports", image: "stadium", lead: true, author: "Leo Huang", read: 5, title: { en: "Mexico beat South Africa in a fiery World Cup opener with three red cards", zh: "墨西哥在三張紅牌亂戰中擊敗南非，拿下世界盃開幕戰" }, dek: { en: "BBC's opening-match recap captured the tournament's immediate intensity as co-host Mexico turned a chaotic night into a statement win.", zh: "BBC 的開幕戰回顧呈現賽事一開場就進入高張力節奏，地主之一墨西哥在混亂之夜拿下關鍵勝利。" } },
    { id: "us-qatar-world-cup-tests", category: "sports", image: "stadium", lead: false, author: "Leo Huang", read: 4, title: { en: "United States and Qatar prepare for key early World Cup tests", zh: "美國與卡達迎接世界盃早期關鍵考驗" }, dek: { en: "AP's June 13 preview framed both matches as important checkpoints in a tournament expanded in scale and pressure.", zh: "美聯社 6 月 13 日前瞻指出，在賽事規模與壓力都擴大的背景下，兩隊首戰都是重要檢驗點。" } },
    { id: "knicks-finals-comeback", category: "sports", image: "stadium", lead: false, author: "Leo Huang", read: 4, title: { en: "Knicks complete the biggest comeback in NBA Finals history", zh: "尼克完成 NBA 總冠軍賽史上最大逆轉" }, dek: { en: "Reuters said OG Anunoby's late tip-in capped a stunning rally and deepened New York's sense that a title run is suddenly real.", zh: "路透報導，阿努諾比最後補籃完成驚人逆轉，也讓紐約更相信冠軍夢正逐步成真。" } },
    { id: "serena-queens-return", category: "sports", image: "stadium", lead: false, author: "Leo Huang", read: 4, title: { en: "Serena Williams wins on her return and weighs a Wimbledon comeback", zh: "小威廉絲復出首戰告捷，並評估是否重返溫布頓" }, dek: { en: "Reuters reported the American icon returned to competition after nearly four years away, instantly altering the conversation ahead of the grass-court major.", zh: "路透指出，這位美國傳奇相隔近四年重返賽場，立刻改變草地大滿貫前的討論焦點。" } },

    { id: "taiwan-shipping-harassment", category: "shipping", image: "shipping", lead: false, author: "Daniel Ko", read: 5, title: { en: "Taiwan says Chinese coast guard harassed commercial shipping off its coast", zh: "台灣稱中國海警在近海騷擾商業船舶" }, dek: { en: "Taipei said Chinese vessels demanded details from passing ships and tried to imply jurisdiction over waters used by merchant traffic.", zh: "台北表示，中國船艦向過往船舶索取資訊，並試圖對商船通行水域塑造其具有管轄權的印象。" } },
    { id: "container-rates-soar-iran", category: "shipping", image: "containers", lead: true, author: "Daniel Ko", read: 6, title: { en: "Iran war anxiety sends global container shipping rates sharply higher", zh: "伊朗戰事憂慮推升全球貨櫃運價大幅走高" }, dek: { en: "Reuters reported that war-risk fears and route disruption are pushing up spot prices just as peak season demand begins to build.", zh: "路透報導，戰爭風險與航線受阻正在推高現貨價格，恰逢旺季需求開始升溫。" } },
    { id: "hormuz-trapped-vessels", category: "shipping", image: "shipping", lead: false, author: "Daniel Ko", read: 5, title: { en: "Ships trapped inside Hormuz still need safety guarantees to leave", zh: "受困荷莫茲海峽船舶即使停火仍需安全保證才能離開" }, dek: { en: "Industry executives told Reuters that reopening the strait alone would not be enough if crews and insurers still doubt transit safety.", zh: "業界主管向路透表示，即使海峽重開，若船員與保險商仍對航行安全存疑，船舶仍難以恢復正常流動。" } },
    { id: "burning-shadow-tanker-oman", category: "shipping", image: "shipping", lead: false, author: "Daniel Ko", read: 4, title: { en: "Indian crew airlifted from a burning shadow-fleet tanker off Oman", zh: "印度船員自阿曼外海起火的影子船隊油輪撤離" }, dek: { en: "The Maritime Executive reported the crew abandoned a sanctioned tanker after a fire, highlighting mounting hazards around Gulf shipping lanes.", zh: "《Maritime Executive》報導，船員在油輪失火後撤船，凸顯海灣航道風險正持續上升。" } },
    { id: "yemen-container-ship-fire", category: "shipping", image: "containers", lead: false, author: "Daniel Ko", read: 4, title: { en: "Container ship exchanges fire with armed boat near Yemen coast", zh: "貨櫃船在葉門外海與武裝船艇交火" }, dek: { en: "Regional maritime reports said the latest confrontation underscored how quickly commercial shipping can be pulled into security crises.", zh: "區域海事通報指出，最新衝突再次說明商船極易被捲入安全危機。" } },

    { id: "tsmc-talent-water", category: "supply-chain", image: "factory", lead: true, author: "Nina Shah", read: 6, title: { en: "TSMC warns talent and water shortages could become Taiwan's next supply-chain bottlenecks", zh: "台積電警告人才與用水短缺恐成台灣下一個供應鏈瓶頸" }, dek: { en: "At a new science park event, the chipmaker's chairman said sustaining the AI boom will require deeper investment in people and basic resources.", zh: "在新科學園區活動上，這家晶片龍頭指出，要支撐 AI 熱潮，必須更大幅投資人才與基礎資源。" } },
    { id: "us-forced-labor-tariffs", category: "supply-chain", image: "warehouse", lead: false, author: "Nina Shah", read: 5, title: { en: "U.S. proposes new tariffs on 60 economies over forced-labour concerns", zh: "美國以強迫勞動疑慮為由，擬對 60 個經濟體加徵新關稅" }, dek: { en: "The move adds another compliance layer for companies already struggling to trace labour conditions deep across their supplier networks.", zh: "這項措施讓原本就難以追蹤深層供應網勞動條件的企業，再多一層合規壓力。" } },
    { id: "forced-labor-rules-compared", category: "supply-chain", image: "policy", lead: false, author: "Nina Shah", read: 4, title: { en: "New U.S. action revives comparisons with Europe's and Britain's forced-labour rules", zh: "美國新措施再度引發與歐洲、英國強迫勞動規範的比較" }, dek: { en: "Reuters outlined how the U.S., EU and Britain are building overlapping but different systems that global suppliers must now navigate.", zh: "路透整理指出，美國、歐盟與英國正建立彼此重疊但不盡相同的制度，全球供應商如今必須一一應對。" } },
    { id: "china-ecommerce-push-stalls", category: "supply-chain", image: "warehouse", lead: false, author: "Nina Shah", read: 5, title: { en: "China's global e-commerce drive loses momentum as war lifts logistics costs", zh: "戰事推升物流成本，中國全球電商擴張動能放緩" }, dek: { en: "Reuters said higher transport costs and softer overseas demand are squeezing the economics behind fast cross-border retail expansion.", zh: "路透指出，更高的運輸成本與較弱的海外需求，正在擠壓跨境零售快速擴張的經濟基礎。" } },
    { id: "asia-factories-stockpile", category: "supply-chain", image: "factory", lead: false, author: "Nina Shah", read: 5, title: { en: "Asian factories build buffers as conflict-driven supply shocks spread", zh: "衝突引發供應衝擊擴散，亞洲工廠加速建立庫存緩衝" }, dek: { en: "Reuters found firms are stockpiling inputs and adjusting procurement plans as higher prices and slower deliveries ripple through manufacturing.", zh: "路透指出，隨著高價與延遲交貨衝擊製造業，企業正囤積原料並調整採購安排。" } },

    { id: "taiwan-cbank-stability", category: "economy-markets", image: "market", lead: false, author: "Priya Raman", read: 4, title: { en: "Taiwan's central bank says it will act in time to preserve financial stability", zh: "台灣央行表示將適時出手維持金融穩定" }, dek: { en: "Officials pointed to tariff uncertainty and currency-market pressure, while signaling readiness to calm volatility if needed.", zh: "官員指出關稅不確定性與匯市壓力正在升高，並釋出必要時將穩定波動的訊號。" } },
    { id: "equities-oil-inflation", category: "economy-markets", image: "market", lead: true, author: "Priya Raman", read: 6, title: { en: "Global equities slide while oil jumps as inflation and Iran tensions rattle markets", zh: "通膨與伊朗緊張局勢擾動市場，全球股市下跌、油價上揚" }, dek: { en: "Reuters reported investors were repricing risk across stocks, bonds and commodities as war and price pressures reinforced each other.", zh: "路透報導，戰事與物價壓力互相強化，投資人正重新調整股票、債券與大宗商品的風險定價。" } },
    { id: "fed-hold-rates-poll", category: "economy-markets", image: "market", lead: false, author: "Priya Raman", read: 5, title: { en: "Reuters poll shows the Fed is now expected to hold rates through 2026", zh: "路透調查顯示，聯準會如今被預期將在 2026 年維持利率不變" }, dek: { en: "Economists have pared back rate-cut expectations as war-linked inflation risks appear more persistent than many had hoped.", zh: "隨著與戰事相關的通膨風險看來比預期更持久，經濟學家已下修對降息的期待。" } },
    { id: "ecb-insurance-hike", category: "economy-markets", image: "market", lead: false, author: "Priya Raman", read: 5, title: { en: "ECB delivers its first rate hike in nearly three years", zh: "歐洲央行近三年來首度升息" }, dek: { en: "Policymakers moved to contain war-driven inflation before energy costs feed more deeply into the broader euro-zone economy.", zh: "決策官員出手抑制戰爭推升的通膨，以防能源成本更深地滲入歐元區整體經濟。" } },
    { id: "spacex-ipo-debut", category: "economy-markets", image: "market", lead: false, author: "Priya Raman", read: 5, title: { en: "SpaceX surges in a record market debut after its historic IPO", zh: "SpaceX 歷史性 IPO 後首日大漲，寫下紀錄級上市表現" }, dek: { en: "The blockbuster float became a fresh test of investor appetite for giant growth stories even in a more uncertain rate environment.", zh: "這宗重量級上市案成為檢驗投資人是否仍願意追逐超大型成長故事的新指標，即使利率環境更不確定。" } },

    { id: "taiwan-hot-dry-summer", category: "energy-climate", image: "energy", lead: false, author: "Amara Okafor", read: 4, title: { en: "Taiwan warns of a hotter, drier summer after an unusually wet June", zh: "台灣預警：濕六月過後，夏季恐更炎熱乾燥" }, dek: { en: "The Central Weather Administration's seasonal outlook reinforced concerns about heat stress, water management and power demand in the months ahead.", zh: "中央氣象署季節展望再次提醒，未來數月的高溫壓力、用水管理與用電需求都將面臨考驗。" } },
    { id: "opec-demand-cut", category: "energy-climate", image: "energy", lead: true, author: "Amara Okafor", read: 5, title: { en: "OPEC cuts its 2026 oil demand growth forecast for a second straight month", zh: "OPEC 連續第二個月下修 2026 年石油需求成長預測" }, dek: { en: "The producer group said weaker growth expectations and the war's disruptions are clouding the medium-term outlook for energy markets.", zh: "產油國集團指出，成長預期轉弱與戰事干擾正讓能源市場的中期前景更顯不明。" } },
    { id: "opec-july-output-hike", category: "energy-climate", image: "energy", lead: false, author: "Amara Okafor", read: 4, title: { en: "OPEC+ still opts for a modest July output increase", zh: "OPEC+ 仍決定在 7 月小幅增產" }, dek: { en: "The move showed producers trying to balance tighter supply, geopolitical disruption and concern about future demand.", zh: "這項決定顯示產油國正試圖在供應緊張、地緣政治干擾與未來需求疑慮之間取得平衡。" } },
    { id: "germany-power-growth", category: "energy-climate", image: "energy", lead: false, author: "Amara Okafor", read: 4, title: { en: "Germany's power growth offers a possible lift to its industrial engine", zh: "德國發電成長為工業引擎帶來可能支撐" }, dek: { en: "Reuters argued that stronger electricity output could provide relief to manufacturers still dealing with high input costs and weak momentum.", zh: "路透分析認為，發電增長可能為仍承受高成本與低動能的製造業提供一些緩衝。" } },
    { id: "trans-mountain-full-capacity", category: "energy-climate", image: "infrastructure", lead: false, author: "Amara Okafor", read: 4, title: { en: "Canada's Trans Mountain pipeline reaches full capacity sooner than expected", zh: "加拿大 Trans Mountain 管線比預期更快達到滿載" }, dek: { en: "Higher Asian demand and Hormuz disruption have boosted interest in non-Middle East crude routes, tightening pipeline use.", zh: "亞洲需求升高與荷莫茲受阻，提升了市場對中東以外原油路線的興趣，也推高管線使用率。" } },

    { id: "taiwan-ai-chip-curbs", category: "policy-regulation", image: "policy", lead: true, author: "Leila Haddad", read: 6, title: { en: "Taiwan weighs tighter AI chip export curbs on China", zh: "台灣評估對中國祭出更嚴格 AI 晶片出口限制" }, dek: { en: "Taipei is considering broader controls that would give authorities new legal tools to prosecute diversion and smuggling of advanced hardware.", zh: "台北正考慮更全面的管制，讓主管機關取得新的法律工具，以追究先進硬體轉運與走私行為。" } },
    { id: "sec-best-execution", category: "policy-regulation", image: "policy", lead: false, author: "Leila Haddad", read: 4, title: { en: "U.S. SEC proposes scrapping long-standing best-execution stock-trade rules", zh: "美國證管會提議取消實施多年的股票最佳執行規則" }, dek: { en: "The proposal marks a significant regulatory rethink for Wall Street market structure and how trade quality should be supervised.", zh: "這項提案意味華爾街市場結構與交易品質監管方式可能迎來重大重整。" } },
    { id: "visa-mastercard-settlement", category: "policy-regulation", image: "policy", lead: false, author: "Leila Haddad", read: 4, title: { en: "Judge grants preliminary approval to Visa and Mastercard's $38 billion swipe-fee deal", zh: "法官初步批准 Visa 與 Mastercard 的 380 億美元刷卡手續費和解案" }, dek: { en: "The revised settlement revives one of the largest antitrust payment disputes in the U.S. and will be watched closely by merchants and banks.", zh: "這份修訂後的和解方案讓美國最大規模的支付反壟斷爭議之一再度成為焦點，商家與銀行都將密切關注。" } },
    { id: "apple-india-antitrust", category: "policy-regulation", image: "policy", lead: false, author: "Leila Haddad", read: 4, title: { en: "Apple agrees to submit India financials in an antitrust investigation", zh: "蘋果同意在印度反壟斷調查中提交財務資料" }, dek: { en: "The step could advance a long-running probe into whether the company used its market power unfairly in the country's app ecosystem.", zh: "此舉可能推進一項長期調查，聚焦蘋果是否在當地 App 生態系中不公平地運用市場支配力。" } },
    { id: "meta-whatsapp-access", category: "policy-regulation", image: "policy", lead: false, author: "Leila Haddad", read: 4, title: { en: "EU orders Meta to open WhatsApp access to rival AI chatbots during antitrust probe", zh: "歐盟命 Meta 在反壟斷調查期間向競爭 AI 聊天機器人開放 WhatsApp 存取" }, dek: { en: "The interim measure shows regulators are moving faster to shape competition in AI markets before dominance becomes entrenched.", zh: "這項臨時措施顯示，監管機關正更快介入塑造 AI 市場競爭，以免壟斷格局提前定型。" } },

    { id: "taiwan-cyber-mou", category: "cybersecurity", image: "cyber", lead: false, author: "Ethan Lin", read: 4, title: { en: "Taiwan's cybersecurity institute signs a new cooperation pact with Microsoft", zh: "台灣國家資通安全研究院與微軟簽署新合作協議" }, dek: { en: "Officials said the partnership will strengthen threat hunting, anomaly detection and resilience across government-facing security systems.", zh: "官員表示，這項合作將強化政府相關資安系統的威脅獵捕、異常偵測與整體韌性。" } },
    { id: "us-three-day-fix-window", category: "cybersecurity", image: "cyber", lead: true, author: "Ethan Lin", read: 5, title: { en: "U.S. cuts the deadline for fixing the most serious cyber flaws to three days", zh: "美國把修補最嚴重資安漏洞的期限縮短至三天" }, dek: { en: "Reuters reported the tighter federal timeline reflects concern that AI-assisted attacks are compressing the window between discovery and exploitation.", zh: "路透報導，聯邦政府收緊時限，反映對 AI 輔助攻擊正大幅縮短漏洞從揭露到被利用時間差的憂慮。" } },
    { id: "novo-nordisk-breach", category: "cybersecurity", image: "data", lead: false, author: "Ethan Lin", read: 4, title: { en: "Novo Nordisk says patient data was copied in a clinical-trial cyber incident", zh: "諾和諾德表示，臨床試驗相關資安事件導致病患資料遭複製" }, dek: { en: "The disclosure adds to concern over how medical research data and sensitive health records are being targeted by intruders.", zh: "這起揭露加深外界對醫療研究資料與敏感健康紀錄正成為攻擊目標的擔憂。" } },
    { id: "russian-hacker-extradited", category: "cybersecurity", image: "cyber", lead: false, author: "Ethan Lin", read: 4, title: { en: "U.S. charges a suspected Russian hacker extradited from Thailand", zh: "美國起訴一名自泰國引渡的俄羅斯籍疑似駭客" }, dek: { en: "Prosecutors said the suspect helped facilitate a wider cyber campaign, highlighting the cross-border nature of criminal digital networks.", zh: "檢方表示，這名嫌犯協助推動更大規模的網攻行動，凸顯數位犯罪網絡的跨境特性。" } },
    { id: "fox-rothschild-class-action", category: "cybersecurity", image: "cyber", lead: false, author: "Ethan Lin", read: 4, title: { en: "Law firm Fox Rothschild faces class action after a data breach", zh: "Fox Rothschild 律師事務所資料外洩後面臨集體訴訟" }, dek: { en: "The suit ties the incident to a ransomware group that the FBI says has repeatedly targeted law firms handling sensitive client files.", zh: "這起訴訟將事件指向一個勒索團體；FBI 指出，該組織持續鎖定掌握敏感客戶檔案的律所。" } },

    { id: "taiwan-port-upgrade-plan", category: "logistics-infrastructure", image: "infrastructure", lead: true, author: "Sofia Reyes", read: 5, title: { en: "Taiwan launches a 73-project plan to upgrade outlying-island port infrastructure", zh: "台灣啟動 73 項工程計畫，升級離島港口基礎設施" }, dek: { en: "The transport ministry said investment in Budai, Penghu, Kinmen and Matsu is meant to raise competitiveness and align port facilities with sustainability goals.", zh: "交通部表示，對布袋、澎湖、金門與馬祖的投資，旨在提升競爭力並讓港口設施更符合永續目標。" } },
    { id: "detroit-windsor-bridge-delay", category: "logistics-infrastructure", image: "infrastructure", lead: false, author: "Sofia Reyes", read: 4, title: { en: "Opening of the new Detroit-Windsor bridge is delayed again", zh: "底特律—溫莎新橋啟用再度延後" }, dek: { en: "Reuters said the $4.7 billion crossing remains strategically important for North American trade even as politics complicate its launch.", zh: "路透指出，這座 47 億美元的新橋對北美貿易仍具戰略重要性，即使政治因素讓啟用時程更複雜。" } },
    { id: "ukraine-railway-tariffs", category: "logistics-infrastructure", image: "infrastructure", lead: false, author: "Sofia Reyes", read: 5, title: { en: "Ukraine's railway says freight tariffs must rise to repair war-hit finances", zh: "烏克蘭鐵路稱必須調升貨運費率，以修復戰爭重創的財務" }, dek: { en: "The state railway says higher tariffs are needed to restore finances, maintain service and complete a debt restructuring amid continued attacks.", zh: "國營鐵路表示，在持續攻擊下，必須提高費率才能修復財務、維持服務並完成債務重整。" } },
    { id: "channel-tunnel-tax-fight", category: "logistics-infrastructure", image: "infrastructure", lead: false, author: "Sofia Reyes", read: 4, title: { en: "Channel Tunnel owner threatens legal action over a new UK tax hike", zh: "英法海底隧道營運商因英國加稅揚言採取法律行動" }, dek: { en: "The dispute shows how tax policy can quickly spill into the economics of strategic cross-border transport infrastructure.", zh: "這場爭議顯示，稅務政策如何迅速影響跨境戰略運輸設施的營運經濟。" } },
    { id: "sicily-bridge-probe", category: "logistics-infrastructure", image: "infrastructure", lead: false, author: "Sofia Reyes", read: 4, title: { en: "Italian prosecutors open a corruption probe tied to the Sicily bridge plan", zh: "義大利檢方就西西里跨海大橋計畫展開貪腐調查" }, dek: { en: "The investigation adds uncertainty to one of Europe's most politically charged infrastructure proposals.", zh: "這項調查讓歐洲最具政治爭議的基礎建設提案之一，再添新的不確定性。" } }
  ];

  window.DAILY_NEWS_STORIES["2026-06-12"] = [
    { id: "port-twins",      category: "technology",               image: "data",           lead: true,  author: "Iris Park",    read: 7, title: { en: "Digital twins give ports a clearer view of tomorrow",                    zh: "數位分身讓港口更清楚看見明日營運" },    dek: { en: "Virtual models are helping terminal operators test changes before applying them in the physical world.",                         zh: "虛擬模型協助碼頭營運商在實際執行前測試各項變更。" } },
    { id: "canal-recovery",  category: "shipping",                 image: "shipping",       lead: true,  author: "Daniel Ko",    read: 5, title: { en: "Canal traffic recovers, but route planners stay cautious",                zh: "運河通行量回升，航線規劃仍保持謹慎" },  dek: { en: "Improved conditions are restoring capacity while carriers retain alternative plans.",                                            zh: "情況改善使運能逐步恢復，但航商仍保留替代方案。" } },
    { id: "women-football",  category: "sports",                   image: "stadium",        lead: true,  author: "Leo Huang",    read: 4, title: { en: "A new football league builds momentum beyond major cities",                zh: "新足球聯賽在都會區之外累積動能" },      dek: { en: "Community clubs are turning local support into a sustainable national competition.",                                             zh: "社區俱樂部正將地方支持轉化為可持續的全國賽事。" } },
    { id: "port-labor",      category: "international",             image: "meeting",        lead: true,  author: "Maya Chen",    read: 5, title: { en: "Port labor negotiations set a regional precedent",                        zh: "港口勞資談判樹立區域先例" },            dek: { en: "A landmark agreement is reshaping expectations across competing terminals.",                                                     zh: "具里程碑意義的協議正改變競爭碼頭間的預期。" } },
    { id: "sc-visibility",   category: "supply-chain",             image: "warehouse",      lead: true,  author: "Nina Shah",    read: 6, title: { en: "Real-time visibility becomes the new baseline in supply chain",            zh: "即時可視性成為供應鏈新基準" },          dek: { en: "Shippers expect live data on shipment status, and providers are racing to deliver.",                                             zh: "貨主要求即時貨況資訊，服務商正加速回應。" } },
    { id: "bond-markets",    category: "economy-markets",          image: "market",         lead: true,  author: "Priya Raman",  read: 5, title: { en: "Bond markets price in a slower path to lower rates",                      zh: "債市預測降息步伐放緩" },                dek: { en: "Yields are stabilizing as investors accept that central banks will move gradually.",                                             zh: "隨著投資人接受央行將漸進行動，殖利率趨於穩定。" } },
    { id: "shore-power",     category: "energy-climate",           image: "energy",         lead: true,  author: "Amara Okafor", read: 6, title: { en: "Shore-power investment accelerates at major terminals",                    zh: "主要碼頭加速投資岸電設施" },            dek: { en: "Ports are expanding electrical capacity so ships can switch off engines while berthed.",                                         zh: "港口正擴充電力容量，讓船舶靠泊時能關閉引擎。" } },
    { id: "data-standard",   category: "policy-regulation",        image: "policy",         lead: true,  author: "Leila Haddad", read: 4, title: { en: "Regulators seek a common standard for freight data",                      zh: "監管機關推動貨運資料共通標準" },        dek: { en: "The proposal aims to improve transparency while protecting commercially sensitive information.",                                 zh: "這項提案旨在提升透明度，同時保護商業敏感資訊。" } },
    { id: "vendor-access",   category: "cybersecurity",            image: "cyber",          lead: true,  author: "Ethan Lin",    read: 5, title: { en: "Third-party access becomes a frontline security concern",                  zh: "第三方存取成為網路安全第一線風險" },    dek: { en: "Transport operators are tightening controls for vendors connecting to critical systems.",                                        zh: "運輸營運商正收緊供應商連接關鍵系統的管控。" } },
    { id: "rail-links",      category: "logistics-infrastructure", image: "infrastructure", lead: true,  author: "Sofia Reyes",  read: 6, title: { en: "New rail links reshape the economics of regional freight",                 zh: "新鐵路連結重塑區域貨運經濟" },          dek: { en: "Faster inland connections are widening the practical reach of coastal gateways.",                                                zh: "更快速的內陸連結正擴大沿海門戶的實際服務範圍。" } }
  ];

  window.DAILY_NEWS_STORIES["2026-06-11"] = [
    { id: "customs-window",   category: "international",            image: "meeting",        lead: true,  author: "Maya Chen",    read: 5, title: { en: "Neighbors agree on a single window for customs data",                    zh: "鄰近國家同意建立海關資料單一窗口" },    dek: { en: "The agreement aims to reduce delays without weakening border controls.",                                                         zh: "這項協議旨在不削弱邊境管制的前提下減少延誤。" } },
    { id: "secure-sensors",   category: "technology",               image: "technology",     lead: true,  author: "Iris Park",    read: 6, title: { en: "Low-cost sensors bring better visibility to small exporters",              zh: "低成本感測器提升中小出口商的貨況可視性" },dek: { en: "Affordable tracking tools are narrowing the information gap across supply networks.",                                            zh: "平價追蹤工具正縮小供應網絡中的資訊落差。" } },
    { id: "cycling-finals",   category: "sports",                   image: "stadium",        lead: true,  author: "Leo Huang",    read: 3, title: { en: "Cycling finals deliver a surprise finish",                                 zh: "自由車決賽出現意外結果" },              dek: { en: "A late tactical move reshaped the podium in the season's closest race.",                                                         zh: "比賽後段的戰術變化，改寫本季最接近的一場賽事頒獎台。" } },
    { id: "fleet-orders",     category: "shipping",                 image: "containers",     lead: true,  author: "Daniel Ko",    read: 5, title: { en: "Fleet orders shift toward flexible, fuel-ready vessels",                   zh: "船隊訂單轉向彈性且支援新燃料的船舶" },  dek: { en: "Owners are paying for adaptability as fuel choices remain uncertain.",                                                           zh: "面對燃料選擇仍不確定，船東更願意為適應能力投資。" } },
    { id: "nearshoring",      category: "supply-chain",             image: "factory",        lead: true,  author: "Nina Shah",    read: 7, title: { en: "Nearshoring matures from slogan into operating model",                    zh: "近岸外包從口號走向實際營運模式" },      dek: { en: "Companies are learning where regional production improves service and where it adds cost.",                                      zh: "企業逐漸掌握區域生產在哪些環節改善服務，又在哪些環節增加成本。" } },
    { id: "consumer-demand",  category: "economy-markets",          image: "market",         lead: true,  author: "Priya Raman",  read: 5, title: { en: "Consumer demand holds, but spending patterns diverge",                    zh: "消費需求維持韌性，但支出模式出現分化" },dek: { en: "Households remain active while becoming more selective about discretionary purchases.",                                           zh: "家庭消費仍然活躍，但對非必要支出變得更為謹慎。" } },
    { id: "grid-storage",     category: "energy-climate",           image: "energy",         lead: true,  author: "Amara Okafor", read: 6, title: { en: "Grid storage moves closer to round-the-clock clean power",                zh: "電網儲能推動潔淨能源邁向全天候供應" },  dek: { en: "Longer-duration batteries are beginning to support industrial and logistics facilities.",                                        zh: "長時儲能電池開始支援工業與物流設施的電力需求。" } },
    { id: "carbon-reporting", category: "policy-regulation",        image: "policy",         lead: true,  author: "Leila Haddad", read: 5, title: { en: "Carbon reporting rules reach smaller suppliers",                          zh: "碳揭露規範延伸至中小型供應商" },        dek: { en: "Large buyers are passing new documentation requirements deeper into their networks.",                                            zh: "大型買方正將新的文件要求延伸至更深層的供應網絡。" } },
    { id: "cargo-ransomware", category: "cybersecurity",            image: "cyber",          lead: true,  author: "Ethan Lin",    read: 6, title: { en: "Cargo networks rehearse for ransomware disruption",                       zh: "貨運網絡演練勒索軟體中斷情境" },        dek: { en: "Tabletop exercises are testing whether operations can continue when core systems go offline.",                                   zh: "桌上演練正測試核心系統離線時，營運是否仍能持續。" } },
    { id: "warehouse-power",  category: "logistics-infrastructure", image: "infrastructure", lead: true,  author: "Sofia Reyes",  read: 5, title: { en: "Warehouse growth puts local power grids under pressure",                  zh: "倉儲成長為地方電網帶來壓力" },          dek: { en: "Automation, cooling and vehicle charging are changing infrastructure requirements for logistics parks.",                         zh: "自動化、冷卻與車輛充電正改變物流園區的基礎建設需求。" } }
  ];

  window.DAILY_NEWS_STORIES["2026-06-10"] = [
    { id: "city-partnership",  category: "international",            image: "city",           lead: true,  author: "Maya Chen",    read: 5, title: { en: "Port cities form a climate adaptation partnership",                     zh: "港口城市成立氣候調適合作夥伴關係" },    dek: { en: "Municipal leaders will share data and financing models for resilient waterfronts.",                                              zh: "城市領袖將共享資料與融資模式，打造更具韌性的濱水區。" } },
    { id: "open-logistics",    category: "technology",               image: "data",           lead: true,  author: "Iris Park",    read: 4, title: { en: "Open logistics standards gain industry support",                          zh: "開放物流標準獲得產業支持" },            dek: { en: "Common formats promise easier data exchange between carriers, ports and customers.",                                             zh: "共通格式有望簡化航商、港口與客戶之間的資料交換。" } },
    { id: "marathon-heat",     category: "sports",                   image: "stadium",        lead: true,  author: "Leo Huang",    read: 4, title: { en: "Marathon organizers redesign races for a warmer climate",                zh: "馬拉松主辦單位因應暖化重新設計賽事" },  dek: { en: "Earlier starts, shaded routes and new medical protocols are becoming standard.",                                                zh: "提早起跑、遮蔭路線與新醫療程序正逐漸成為標準。" } },
    { id: "seafarer-training", category: "shipping",                 image: "shipping",       lead: true,  author: "Daniel Ko",    read: 6, title: { en: "Seafarer training catches up with the low-carbon fleet",                 zh: "船員訓練加速跟上低碳船隊需求" },        dek: { en: "New fuels require updated safety skills throughout maritime operations.",                                                        zh: "新燃料要求海運作業全面更新安全技能。" } },
    { id: "supplier-finance",  category: "supply-chain",             image: "warehouse",      lead: true,  author: "Nina Shah",    read: 5, title: { en: "Faster supplier finance strengthens smaller partners",                    zh: "加速供應商融資，強化中小型合作夥伴" },  dek: { en: "Digital approval systems are shortening payment cycles across complex networks.",                                                zh: "數位審核系統正縮短複雜供應網絡中的付款週期。" } },
    { id: "freight-index",     category: "economy-markets",          image: "market",         lead: true,  author: "Priya Raman",  read: 4, title: { en: "Freight indicators point to a steadier second half",                     zh: "貨運指標顯示下半年走勢更趨穩定" },      dek: { en: "Volumes and booking data suggest demand is normalizing across several major corridors.",                                         zh: "貨量與訂艙資料顯示，多條主要走廊的需求正逐步正常化。" } },
    { id: "port-solar",        category: "energy-climate",           image: "energy",         lead: true,  author: "Amara Okafor", read: 5, title: { en: "Ports turn unused rooftops into local energy assets",                    zh: "港口將閒置屋頂轉化為在地能源資產" },    dek: { en: "Solar installations are helping terminals manage daytime power demand and charging loads.",                                     zh: "太陽能設施協助碼頭管理日間用電與充電負載。" } },
    { id: "competition-review",category: "policy-regulation",        image: "policy",         lead: true,  author: "Leila Haddad", read: 5, title: { en: "Competition review examines consolidation in logistics",                  zh: "競爭審查聚焦物流產業整併" },            dek: { en: "Authorities are studying whether recent deals affect pricing, access and service resilience.",                                   zh: "主管機關正研究近期交易是否影響價格、市場進入與服務韌性。" } },
    { id: "identity-controls", category: "cybersecurity",            image: "cyber",          lead: true,  author: "Ethan Lin",    read: 4, title: { en: "Identity controls replace passwords across transport systems",             zh: "身分控管逐步取代運輸系統密碼" },        dek: { en: "Operators are adopting stronger authentication for workers, contractors and remote support teams.",                              zh: "營運商正為員工、承包商與遠端支援團隊採用更強的驗證機制。" } },
    { id: "urban-delivery",    category: "logistics-infrastructure", image: "infrastructure", lead: true,  author: "Sofia Reyes",  read: 6, title: { en: "Cities redesign loading zones for a delivery economy",                   zh: "城市為配送經濟重新設計裝卸空間" },      dek: { en: "Digital booking and shared curb space aim to reduce congestion without slowing commerce.",                                      zh: "數位預約與共享路邊空間旨在不拖慢商業活動的情況下降低壅塞。" } }
  ];

  // Notify waiting scripts that this month's stories are ready
  document.dispatchEvent(new CustomEvent("dn:stories-loaded"));
})();
