// data-2026-06.js — stories for June 2026.
// Loaded on-demand by app.js and edition.js; never loaded on its own.
// To add a new day: append a new object to window.DAILY_NEWS_STORIES["YYYY-MM-DD"].

(function () {
  window.DAILY_NEWS_STORIES = window.DAILY_NEWS_STORIES || {};

  window.DAILY_NEWS_STORIES["2026-06-13"] = [
    { id: "strait-dialogue",   category: "international",            image: "meeting",        lead: true,  author: "Maya Chen",    read: 6, title: { en: "Regional leaders reopen a practical channel for dialogue",              zh: "區域領袖重啟務實對話管道" },          dek: { en: "A smaller diplomatic forum is creating room for progress on trade, security and climate resilience.",                            zh: "小型外交論壇為貿易、安全與氣候韌性議題創造新的進展空間。" } },
    { id: "efficient-ai",      category: "technology",               image: "technology",     lead: true,  author: "Iris Park",    read: 7, title: { en: "The quiet race to make artificial intelligence use less energy",          zh: "降低人工智慧耗能的無聲競賽" },          dek: { en: "Researchers are finding that smaller, specialized systems can deliver more useful results with less computing power.",            zh: "研究人員發現，更小型且專門化的系統能以較少算力產出更實用的成果。" } },
    { id: "stadium-data",      category: "sports",                   image: "stadium",        lead: true,  author: "Leo Huang",    read: 5, title: { en: "How live data is changing decisions on the field",                       zh: "即時數據如何改變賽場決策" },            dek: { en: "Coaches are balancing real-time analytics with the experience and intuition of athletes.",                                       zh: "教練開始在即時分析、運動員經驗與直覺之間尋找平衡。" } },
    { id: "green-corridor",    category: "shipping",                 image: "shipping",       lead: true,  author: "Daniel Ko",    read: 8, title: { en: "Asia's first green shipping corridors move from plan to practice",        zh: "亞洲綠色航運走廊從規劃邁向實踐" },      dek: { en: "Ports and carriers are coordinating fuel, infrastructure and schedules to cut emissions on major routes.",                       zh: "港口與航商正協調燃料、基礎建設與船期，以降低主要航線的碳排放。" } },
    { id: "inventory-reset",   category: "supply-chain",             image: "warehouse",      lead: true,  author: "Nina Shah",    read: 6, title: { en: "Companies rethink inventory after years of disruption",                   zh: "企業在多年動盪後重新思考庫存策略" },    dek: { en: "The new model favors visibility and flexible regional networks over simply holding more stock.",                                 zh: "新模式不再只是增加庫存，而是強調可視性與彈性的區域網絡。" } },
    { id: "rates-outlook",     category: "economy-markets",          image: "market",         lead: true,  author: "Priya Raman",  read: 6, title: { en: "Markets recalibrate as the interest-rate outlook steadies",              zh: "利率前景趨穩，市場重新調整布局" },      dek: { en: "Investors are shifting attention from short-term signals to earnings, productivity and long-term demand.",                       zh: "投資人正將焦點從短期訊號轉向企業獲利、生產力與長期需求。" } },
    { id: "clean-fuels",       category: "energy-climate",           image: "energy",         lead: true,  author: "Amara Okafor", read: 7, title: { en: "Clean-fuel projects confront the challenge of commercial scale",           zh: "潔淨燃料計畫面臨商業規模化挑戰" },      dek: { en: "Developers are moving beyond pilot plants, but financing and reliable demand remain decisive.",                                 zh: "開發商正走出試驗階段，但融資與穩定需求仍是成敗關鍵。" } },
    { id: "trade-rules",       category: "policy-regulation",        image: "policy",         lead: true,  author: "Leila Haddad", read: 5, title: { en: "New trade rules put supply-chain disclosure in focus",                    zh: "新貿易規範聚焦供應鏈資訊揭露" },        dek: { en: "Companies face tighter requirements to document sourcing, emissions and labor conditions.",                                      zh: "企業面臨更嚴格要求，必須記錄採購來源、碳排放與勞動條件。" } },
    { id: "port-security",     category: "cybersecurity",            image: "cyber",          lead: true,  author: "Ethan Lin",    read: 6, title: { en: "Ports strengthen cyber defenses around operational technology",             zh: "港口強化營運科技的網路防禦" },          dek: { en: "Operators are separating critical systems and rehearsing recovery plans as digital exposure grows.",                             zh: "隨著數位風險增加，營運商正隔離關鍵系統並演練復原計畫。" } },
    { id: "freight-hubs",      category: "logistics-infrastructure", image: "infrastructure", lead: true,  author: "Sofia Reyes",  read: 7, title: { en: "Inland freight hubs emerge as the next capacity frontier",                zh: "內陸貨運樞紐成為下一個運能成長前線" },  dek: { en: "Rail connections and automated yards are extending port capacity far beyond the waterfront.",                                    zh: "鐵路連結與自動化堆場，正將港口運能延伸至濱水區之外。" } },
    { id: "port-ai",           category: "technology",               image: "data",           lead: false, author: "Mina Sato",    read: 4, title: { en: "Ports turn to AI to predict the next bottleneck",                         zh: "港口利用人工智慧預測下一個壅塞點" },    dek: { en: "New forecasting tools combine vessel, weather and terminal data to improve daily planning.",                                    zh: "新預測工具整合船舶、天候與碼頭資料，改善每日營運規劃。" } },
    { id: "container-rates",   category: "shipping",                 image: "containers",     lead: false, author: "Owen Bell",    read: 5, title: { en: "Container rates stabilize as capacity returns",                            zh: "運力回升，貨櫃運價逐步穩定" },          dek: { en: "Shippers remain cautious, but recent capacity additions are easing pressure on key lanes.",                                     zh: "貨主仍保持謹慎，但新增運力正緩解主要航線的壓力。" } },
    { id: "resilient-suppliers",category: "supply-chain",            image: "factory",        lead: false, author: "Priya Raman",  read: 5, title: { en: "Supplier diversity becomes a board-level priority",                       zh: "供應商多元化成為董事會層級議題" },      dek: { en: "Procurement teams are measuring resilience alongside cost, quality and delivery.",                                               zh: "採購團隊開始將韌性與成本、品質、交付能力一併衡量。" } }
  ];

  window.DAILY_NEWS_STORIES["2026-06-12"] = [
    { id: "port-twins",      category: "technology",               image: "data",           lead: true,  author: "Iris Park",    read: 7, title: { en: "Digital twins give ports a clearer view of tomorrow",                    zh: "數位分身讓港口更清楚看見明日營運" },    dek: { en: "Virtual models are helping terminal operators test changes before applying them in the physical world.",                         zh: "虛擬模型協助碼頭營運商在實際執行前測試各項變更。" } },
    { id: "canal-recovery",  category: "shipping",                 image: "shipping",       lead: true,  author: "Daniel Ko",    read: 5, title: { en: "Canal traffic recovers, but route planners stay cautious",                zh: "運河通行量回升，航線規劃仍保持謹慎" },  dek: { en: "Improved conditions are restoring capacity while carriers retain alternative plans.",                                            zh: "情況改善使運能逐步恢復，但航商仍保留替代方案。" } },
    { id: "women-football",  category: "sports",                   image: "stadium",        lead: true,  author: "Leo Huang",    read: 4, title: { en: "A new football league builds momentum beyond major cities",                zh: "新足球聯賽在都會區之外累積動能" },      dek: { en: "Community clubs are turning local support into a sustainable national competition.",                                             zh: "社區俱樂部正將地方支持轉化為可持續的全國賽事。" } },
    { id: "port-labor",      category: "international",             image: "meeting",        lead: true,  author: "Maya Chen",    read: 5, title: { en: "Port labor negotiations set a regional precedent",                        zh: "港口勞資談判樹立區域先例" },            dek: { en: "A landmark agreement is reshaping expectations across competing terminals.",                                                     zh: "具里程碑意義的協議正改變競爭碼頭間的預期。" } },
    { id: "sc-visibility",   category: "supply-chain",             image: "warehouse",      lead: true,  author: "Nina Shah",    read: 6, title: { en: "Real-time visibility becomes the new baseline in supply chain",            zh: "即時可視性成為供應鏈新基準" },          dek: { en: "Shippers expect live data on shipment status, and providers are racing to deliver.",                                             zh: "貨主要求即時貨況資訊，服務商正加速回應。" } },
    { id: "bond-markets",    category: "economy-markets",          image: "market",         lead: true,  author: "Priya Raman",  read: 5, title: { en: "Bond markets price in a slower path to lower rates",                      zh: "債市預測降息步伐放緩" },                dek: { en: "Yields are stabilizing as investors accept that central banks will move gradually.",                                             zh: "隨著投資人接受央行將漸進行動，殖利率趨於穩定。" } },
    { id: "shore-power",     category: "energy-climate",           image: "energy",         lead: true,  author: "Amara Okafor", read: 6, title: { en: "Shore-power investment accelerates at major terminals",                    zh: "主要碼頭加速投資岸電設施" },            dek: { en: "Ports are expanding electrical capacity so ships can switch off engines while berthed.",                                         zh: "港口正擴充電力容量，讓船舶靠泊時能關閉引擎。" } },
    { id: "data-standard",   category: "policy-regulation",        image: "policy",         lead: true,  author: "Leila Haddad", read: 4, title: { en: "Regulators seek a common standard for freight data",                      zh: "監管機關推動貨運資料共通標準" },        dek: { en: "The proposal aims to improve transparency while protecting commercially sensitive information.",                                 zh: "這項提案旨在提升透明度，同時保護商業敏感資訊。" } },
    { id: "vendor-access",   category: "cybersecurity",            image: "cyber",          lead: true,  author: "Ethan Lin",    read: 5, title: { en: "Third-party access becomes a frontline security concern",                  zh: "第三方存取成為網路安全第一線風險" },    dek: { en: "Transport operators are tightening controls for vendors connecting to critical systems.",                                        zh: "運輸營運商正收緊供應商連接關鍵系統的管控。" } },
    { id: "rail-links",      category: "logistics-infrastructure", image: "infrastructure", lead: true,  author: "Sofia Reyes",  read: 6, title: { en: "New rail links reshape the economics of regional freight",                 zh: "新鐵路連結重塑區域貨運經濟" },          dek: { en: "Faster inland connections are widening the practical reach of coastal gateways.",                                                zh: "更快速的內陸連結正擴大沿海門戶的實際服務範圍。" } }
  ];

  window.DAILY_NEWS_STORIES["2026-06-11"] = [
    { id: "customs-window",   category: "international",            image: "meeting",        lead: true,  author: "Maya Chen",    read: 5, title: { en: "Neighbors agree on a single window for customs data",                    zh: "鄰近國家同意建立海關資料單一窗口" },    dek: { en: "The agreement aims to reduce delays without weakening border controls.",                                                         zh: "這項協議旨在不削弱邊境管制的前提下減少延誤。" } },
    { id: "secure-sensors",   category: "technology",               image: "technology",     lead: true,  author: "Iris Park",    read: 6, title: { en: "Low-cost sensors bring better visibility to small exporters",              zh: "低成本感測器提升中小出口商的貨況可視性" },dek: { en: "Affordable tracking tools are narrowing the information gap across supply networks.",                                            zh: "平價追蹤工具正縮小供應網絡中的資訊落差。" } },
    { id: "cycling-finals",   category: "sports",                   image: "stadium",        lead: true,  author: "Leo Huang",    read: 3, title: { en: "Cycling finals deliver a surprise finish",                                 zh: "自由車決賽出現意外結果" },              dek: { en: "A late tactical move reshaped the podium in the season's closest race.",                                                         zh: "比賽後段的戰術變化，改寫本季最接近的一場賽事頒獎台。" } },
    { id: "fleet-orders",     category: "shipping",                 image: "containers",     lead: true,  author: "Daniel Ko",    read: 5, title: { en: "Fleet orders shift toward flexible, fuel-ready vessels",                   zh: "船隊訂單轉向彈性且支援新燃料的船舶" },  dek: { en: "Owners are paying for adaptability as fuel choices remain uncertain.",                                                           zh: "面對燃料選擇仍不確定，船東更願意為適應能力投資。" } },
    { id: "nearshoring",      category: "supply-chain",             image: "factory",        lead: true,  author: "Nina Shah",    read: 7, title: { en: "Nearshoring matures from slogan into operating model",                    zh: "近岸外包從口號走向實際營運模式" },      dek: { en: "Companies are learning where regional production improves service and where it adds cost.",                                      zh: "企業逐漸掌握區域生產在哪些環節改善服務，又在哪些環節增加成本。" } },
    { id: "consumer-demand",  category: "economy-markets",          image: "market",         lead: true,  author: "Priya Raman",  read: 5, title: { en: "Consumer demand holds, but spending patterns diverge",                    zh: "消費需求維持韌性，但支出模式出現分化" },dek: { en: "Households remain active while becoming more selective about discretionary purchases.",                                           zh: "家庭消費仍然活躍，但對非必要支出變得更為謹慎。" } },
    { id: "grid-storage",     category: "energy-climate",           image: "energy",         lead: true,  author: "Amara Okafor", read: 6, title: { en: "Grid storage moves closer to round-the-clock clean power",                zh: "電網儲能推動潔淨能源邁向全天候供應" },  dek: { en: "Longer-duration batteries are beginning to support industrial and logistics facilities.",                                        zh: "長時儲能電池開始支援工業與物流設施的電力需求。" } },
    { id: "carbon-reporting", category: "policy-regulation",        image: "policy",         lead: true,  author: "Leila Haddad", read: 5, title: { en: "Carbon reporting rules reach smaller suppliers",                          zh: "碳揭露規範延伸至中小型供應商" },        dek: { en: "Large buyers are passing new documentation requirements deeper into their networks.",                                            zh: "大型買方正將新的文件要求延伸至更深層的供應網絡。" } },
    { id: "cargo-ransomware", category: "cybersecurity",            image: "cyber",          lead: true,  author: "Ethan Lin",    read: 6, title: { en: "Cargo networks rehearse for ransomware disruption",                       zh: "貨運網絡演練勒索軟體中斷情境" },        dek: { en: "Tabletop exercises are testing whether operations can continue when core systems go offline.",                                   zh: "桌上演練正測試核心系統離線時，營運是否仍能持續。" } },
    { id: "warehouse-power",  category: "logistics-infrastructure", image: "infrastructure", lead: true,  author: "Sofia Reyes",  read: 5, title: { en: "Warehouse growth puts local power grids under pressure",                  zh: "倉儲成長為地方電網帶來壓力" },          dek: { en: "Automation, cooling and vehicle charging are changing infrastructure requirements for logistics parks.",                         zh: "自動化、冷卻與車輛充電正改變物流園區的基礎建設需求。" } }
  ];

  window.DAILY_NEWS_STORIES["2026-06-10"] = [
    { id: "city-partnership",  category: "international",            image: "city",           lead: true,  author: "Maya Chen",    read: 5, title: { en: "Port cities form a climate adaptation partnership",                     zh: "港口城市成立氣候調適合作夥伴關係" },    dek: { en: "Municipal leaders will share data and financing models for resilient waterfronts.",                                              zh: "城市領袖將共享資料與融資模式，打造更具韌性的濱水區。" } },
    { id: "open-logistics",    category: "technology",               image: "data",           lead: true,  author: "Iris Park",    read: 4, title: { en: "Open logistics standards gain industry support",                          zh: "開放物流標準獲得產業支持" },            dek: { en: "Common formats promise easier data exchange between carriers, ports and customers.",                                             zh: "共通格式有望簡化航商、港口與客戶之間的資料交換。" } },
    { id: "marathon-heat",     category: "sports",                   image: "stadium",        lead: true,  author: "Leo Huang",    read: 4, title: { en: "Marathon organizers redesign races for a warmer climate",                zh: "馬拉松主辦單位因應暖化重新設計賽事" },  dek: { en: "Earlier starts, shaded routes and new medical protocols are becoming standard.",                                                zh: "提早起跑、遮蔭路線與新醫療程序正逐漸成為標準。" } },
    { id: "seafarer-training", category: "shipping",                 image: "shipping",       lead: true,  author: "Daniel Ko",    read: 6, title: { en: "Seafarer training catches up with the low-carbon fleet",                 zh: "船員訓練加速跟上低碳船隊需求" },        dek: { en: "New fuels require updated safety skills throughout maritime operations.",                                                        zh: "新燃料要求海運作業全面更新安全技能。" } },
    { id: "supplier-finance",  category: "supply-chain",             image: "warehouse",      lead: true,  author: "Nina Shah",    read: 5, title: { en: "Faster supplier finance strengthens smaller partners",                    zh: "加速供應商融資，強化中小型合作夥伴" },  dek: { en: "Digital approval systems are shortening payment cycles across complex networks.",                                                zh: "數位審核系統正縮短複雜供應網絡中的付款週期。" } },
    { id: "freight-index",     category: "economy-markets",          image: "market",         lead: true,  author: "Priya Raman",  read: 4, title: { en: "Freight indicators point to a steadier second half",                     zh: "貨運指標顯示下半年走勢更趨穩定" },      dek: { en: "Volumes and booking data suggest demand is normalizing across several major corridors.",                                         zh: "貨量與訂艙資料顯示，多條主要走廊的需求正逐步正常化。" } },
    { id: "port-solar",        category: "energy-climate",           image: "energy",         lead: true,  author: "Amara Okafor", read: 5, title: { en: "Ports turn unused rooftops into local energy assets",                    zh: "港口將閒置屋頂轉化為在地能源資產" },    dek: { en: "Solar installations are helping terminals manage daytime power demand and charging loads.",                                     zh: "太陽能設施協助碼頭管理日間用電與充電負載。" } },
    { id: "competition-review",category: "policy-regulation",        image: "policy",         lead: true,  author: "Leila Haddad", read: 5, title: { en: "Competition review examines consolidation in logistics",                  zh: "競爭審查聚焦物流產業整併" },            dek: { en: "Authorities are studying whether recent deals affect pricing, access and service resilience.",                                   zh: "主管機關正研究近期交易是否影響價格、市場進入與服務韌性。" } },
    { id: "identity-controls", category: "cybersecurity",            image: "cyber",          lead: true,  author: "Ethan Lin",    read: 4, title: { en: "Identity controls replace passwords across transport systems",             zh: "身分控管逐步取代運輸系統密碼" },        dek: { en: "Operators are adopting stronger authentication for workers, contractors and remote support teams.",                              zh: "營運商正為員工、承包商與遠端支援團隊採用更強的驗證機制。" } },
    { id: "urban-delivery",    category: "logistics-infrastructure", image: "infrastructure", lead: true,  author: "Sofia Reyes",  read: 6, title: { en: "Cities redesign loading zones for a delivery economy",                   zh: "城市為配送經濟重新設計裝卸空間" },      dek: { en: "Digital booking and shared curb space aim to reduce congestion without slowing commerce.",                                      zh: "數位預約與共享路邊空間旨在不拖慢商業活動的情況下降低壅塞。" } }
  ];

  // Notify waiting scripts that this month's stories are ready
  document.dispatchEvent(new CustomEvent("dn:stories-loaded"));
})();
